# Generated by Django 3.1.1 on 2020-09-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200929_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_cost',
            new_name='order_total',
        ),
    ]
